<a href="https://colab.research.google.com/github/SiZhan9/MLpy/blob/master/Python_Recap_rl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
!ls

sample_data


In [0]:
!sys_info

/bin/bash: sys_info: command not found


In [0]:
theta = np.random.randn(4) / 2

In [0]:
print(theta)

[ 0.13952406 -0.50760622  0.21429949 -1.01514032]


In [0]:
print(np.random.randn(3,2))

[[ 0.13368806 -0.69348932]
 [-1.45259734  0.56274516]
 [ 0.75527477 -0.55609612]]


In [0]:
V_array = []
for k in range(1000):
  Var1 = np.random.randn(5,5)
  V_array.append(Var1)
V_mean = np.mean(V_array)
print(V_array[800])
print(V_mean)

[[ 0.85380655  1.38139126  1.81542242  1.72888751 -1.35796309]
 [-0.44815787  0.28824341  0.73016737 -1.87574972  0.13735192]
 [-0.79902888 -1.89316586 -0.61002967  1.84679581 -0.68475819]
 [ 0.03799826 -0.97137448  0.28751185  1.56277496  0.3068576 ]
 [-0.14197306 -0.69399399 -0.96067819  0.53853231  0.00347534]]
-0.011208242162441009


In [0]:
!help set

set: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
    Set or unset values of shell options and positional parameters.
    
    Change the value of shell attributes and positional parameters, or
    display the names and values of shell variables.
    
    Options:
      -a  Mark variables which are modified or created for export.
      -b  Notify of job termination immediately.
      -e  Exit immediately if a command exits with a non-zero status.
      -f  Disable file name generation (globbing).
      -h  Remember the location of commands as they are looked up.
      -k  All assignment arguments are placed in the environment for a
          command, not just those that precede the command name.
      -m  Job control is enabled.
      -n  Read commands but do not execute them.
      -o option-name
          Set the variable corresponding to option-name:
              allexport    same as -a
              braceexpand  same as -B
              emacs        use an emacs-style 

In [0]:
import gym

In [0]:
env = gym.make('CartPole-v0')

/usr/local/lib/python3.6/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [0]:
env.reset()

array([ 0.00643725, -0.00718729,  0.03944185,  0.04808632])

In [0]:
box = env.observation_space

In [0]:
box

Box(4,)

NameError: ignored